const routes = {
  home: {
    home: "/",
    features: "/features",
    services: "/services",
    contact: "/contact",
    policy: "/policy",
  },
  auth: {
    login: "/login",
    forgotPassword: "/forgot-password",
    register: "/register",
    authenticate: "/authenticate",
  },
  modals: {
    profile: "/profile",
    tenantDetail: "/customers/tenants/:id",
    roomMembers: "/room/members/:id",
  },
  dashboard: "/dashboard",
  facilities: {
    buildings: "/facilities/buildings",
    buildingsHistory: "/facilities/buildings/history",
    floors: "/facilities/floors",
    floorsHistory: "/facilities/floors/history",
    floorsHistoryId: "/facilities/floors/history/:id",
    floorId: "/facilities/floors/:id",
    rooms: "/facilities/rooms",
    roomId: "/facilities/rooms/:id",
    roomsHistory: "/facilities/rooms/history",
    roomsHistoryId: "/facilities/rooms/history/:id",
  },
  assetMng: {
    assetType: "/asset-management/asset-types",
    asset: "/asset-management/assets",
    assetHistory: "/asset-management/assets/history",
    assetHistoryId: "/asset-management/assets/history/:id",
    assetId: "/asset-management/assets/:id",
    roomAsset: "/asset-management/room-assets",
    roomId: "/asset-management/room-assets/:id",
    roomAssetDetail: "/asset-management/room-assets/detail/:roomId",
  },
  serviceMng: {
    roomService: "/service-management/room-services",
    roomServiceId: "/service-management/room-services/:id",
    roomServiceDetail: "/service-management/room-services/detail/:roomId",
    service: "/service-management/services",
    serviceHistory: "/service-management/services/history",
  },
  customer: {
    vehicles: "/customers/vehicles",
    vehiclesHistory: "/customers/vehicles/history",
    tenants: "/customers/tenants",
    tenantsHistory: "/customers/tenants/history",
    contract: "/customers/contracts",
    contractHistory: "/customers/contracts/history",
    contractDetail: "/customers/contracts/:contractId",
  },
  finance: {
    meter: "/finance/meters",
    meterId: "/finance/meters/:id",
    meterStatisticId: "/finance/meters/statistics/:id",
    meterReading: "/finance/meter-reading",
    meterReadingId: "/finance/meter-reading/:id",
    invoice: "/finance/invoice",
    invoiceHistory: "/finance/invoice/history",
    paymentReceipt: "/finance/payment-receipt",
    invoiceId: "/finance/invoice/:id",
    invoiceViewId: "/finance/invoice/view/:id",
  },
  user: {
    room: "/room",
    roomDetail: "/room/detail/:id",
    invoice: "/invoices",
    paymentReceipt: "/payment-receipts",
    viewInvoice: "/invoices/view/:id",
    invoicePayment: "/invoices/payment/:id",
    paymentCallback: "/payments/payment-callback",
  },
};

export default routes;
